use std::ops::{Deref, DerefMut, RangeInclusive};

use anchor_lang::{prelude::*, InstructionData, ToAccountMetas, ZeroCopy};
use num_traits::{AsPrimitive, PrimInt};

pub mod vrf;

/// Declare a `VrfState` wrapper struct for [`VrfAccountData`].
/// We willuse this struct to interact with the `vrf_sdk`
/// through [`request_randomness`] function.
///
/// User should use this immediately after anchor `declare_id!()` macro.
///
/// Example
/// ```no_run
/// use anchor_lang::prelude::*;
///
/// declare_id!("6trpiXViFkrXFR1F1nMDGMyigUo89c53La2Bpc4mMwyG");
/// vrf_sdk::declare_vrf_state!(VrfState);
/// ```
///
/// We do this because anchor_lang::AccountLoader<'info, T> required
/// that we implements anchor_lang::Owner, which is the program_id
/// but we just a library and implement that is not trivial.
/// So, as a work around we make a wrapper struct in the program itself
/// via macro.
#[macro_export]
macro_rules! declare_vrf_state {
    ($struct_name:ident) => {
        /// Wrapper struct for `vrf_sdk::VrfAccountData`
        ///
        /// Each randomness request should create a new instance of this
        /// struct on-chain, and call (request_randomness)[`vrf_sdk::request_randomness`]
        #[account(zero_copy)]
        #[repr(packed)]
        pub struct $struct_name {
            vrf: $crate::vrf::VrfAccountData,
        }

        impl std::ops::Deref for $struct_name {
            type Target = $crate::vrf::VrfAccountData;

            fn deref(&self) -> &Self::Target {
                &self.vrf
            }
        }

        impl std::ops::DerefMut for $struct_name {
            fn deref_mut(&mut self) -> &mut Self::Target {
                &mut self.vrf
            }
        }
    };
}

/// Account size use when init a new [VrfState](`declare_vrf_state`)
///
/// Example
/// ```no_run
/// #[derive(Accounts)]
/// pub struct RequestRandomness<'info> {
///     #[account(
/// 		init,
/// 		payer = payer,
/// 		space = vrf_sdk::ACCOUNT_SIZE,
/// 		seeds = [
/// 			// Specify PDA seeds
/// 		],
/// 		bump,
/// 	)]
///     vrf: AccountLoader<'info, VrfState>,
///     system_program: Program<'info, System>,
/// }
/// ```
pub const ACCOUNT_SIZE: usize = std::mem::size_of::<vrf::VrfAccountData>() + /* DISCRIMINATOR */ 8;

/// Request a new randomness value.
/// The supplied `VrfState` should be created seperately for each request
///
/// Example
/// ```no_run
/// vrf_sdk::request_randomness(
/// 	&ctx.accounts.vrf,
/// 	// This struct will be auto generated by anchor
/// 	// if you has an struct like
/// 	//
/// 	// #[derive(Accounts)]
/// 	// struct OnRandomnessResponse
/// 	accounts::OnRandomnessResponse {
/// 		vrf: ctx.accounts.vrf.key(),
/// 	},
/// 	// This struct will be auto generated by anchor
/// 	// if you has an instruction call: on_randomness_response
/// 	instruction::OnRandomnessResponse {
///     	params: params,
/// 	},
/// )?;
/// ```
pub fn request_randomness<VRF, CB, IX>(
    vrf: &AccountLoader<'_, VRF>,
    callback: CB,
    callback_ix_data: IX,
) -> anchor_lang::Result<()>
where
    VRF: DerefMut<Target = vrf::VrfAccountData> + ZeroCopy + Owner,
    CB: ToAccountMetas,
    IX: InstructionData,
{
    let vrf_pubkey = vrf.key();
    let vrf = &mut vrf.load_init()?;
    let vrf = vrf.deref_mut();

    vrf.request_timestamp = Clock::get()?.unix_timestamp;
    vrf.callback.program_id = VRF::owner();

    let metas = callback.to_account_metas(None);
    vrf.callback.accounts_len = metas.len() as u32;
    for (i, meta) in metas.iter().enumerate() {
        vrf.callback.accounts[i] = vrf::AccountMetaPacked {
            pubkey: meta.pubkey,
            is_signer: meta.is_signer,
            is_writable: meta.is_writable,
        };
    }

    let ix_data = callback_ix_data.data();
    vrf.callback.ix_data_len = ix_data.len() as u32;
    vrf.callback.ix_data[0..ix_data.len()].copy_from_slice(&ix_data);

    emit!(vrf::VrfRequestRandomness { vrf: vrf_pubkey });
    Ok(())
}

/// Generate a random number from the `VrfState`
/// that satisfy the provided range.
///
/// Example
/// ```no_run
/// 	let vrf = ctx.accounts.vrf.load()?;
///		let result = vrf_sdk::random(vrf, 0..=100)?;
/// 	assert!(0 <= result && result <= 100);
/// ```
pub fn random<VRF, VrfState, Int>(vrf: VRF, range: RangeInclusive<Int>) -> anchor_lang::Result<Int>
where
    VRF: Deref<Target = VrfState>,
    VrfState: Deref<Target = vrf::VrfAccountData>,
    Int: PrimInt + AsPrimitive<i128>,
    i128: AsPrimitive<Int>,
{
    // compile time assertion that `vrf::VrfAccountData::RESULT_BYTE_LEN`
    // must contains at least 16 bytes
    const _: [(); 0 - !(vrf::VrfAccountData::RESULT_BYTE_LEN >= 16) as usize] = [];

    let vrf = vrf.deref().deref();

    // ensure that the vrf has completed
    if vrf.result == [0u8; vrf::VrfAccountData::RESULT_BYTE_LEN] {
        return Err(Error::AnchorError(AnchorError {
            error_name: "VrfNotFulfilled".to_owned(),
            error_code_number: 7777,
            error_msg: "vrf_sdk::random() called on an empty VrfState".to_owned(),
            error_origin: None,
            compared_values: None,
        }));
    }

    // convert the first 16 byte from the result to an i128
    // we assert at compile time that the result contains at least 16 bytes, so unwrap is ok
    let rand = i128::from_be_bytes(vrf.result[0..16].try_into().unwrap());

    // apply the required range
    let bound: i128 = (*range.end() - *range.start()).as_();
    let out = ((rand % bound) + range.start().as_()).as_();
    Ok(out)
}
