use anchor_lang::prelude::*;

declare_id!("6trpiXViFkrXFR1F1nMDGMyigUo89c53La2Bpc4mMwyG");

vrf_sdk::declare_vrf_state!(VrfState);

#[program]
mod anchor_using_vrf {
    use super::*;

    pub fn init(ctx: Context<InitProgram>) -> anchor_lang::Result<()> {
        *ctx.accounts.state = ProgramState {
            owner: ctx.accounts.owner.key(),
            round: 0,
        };

        Ok(())
    }

    pub fn flip_a_coin(ctx: Context<CoinFlipRequest>, bet_amount: u64) -> anchor_lang::Result<()> {
        vrf_sdk::request_randomness(
            &ctx.accounts.vrf,
            // This struct will be auto generated by anchor
            accounts::CoinFlipResult {
                owner: ctx.accounts.state.owner,
                state: ctx.accounts.state.key(),
                user: ctx.accounts.user.key(),
                vrf: ctx.accounts.vrf.key(),
            },
            // This struct will be auto generated by anchor
            instruction::OnCoinFlipped {
                vrf_round: ctx.accounts.state.round,
                bet_amount: bet_amount,
            },
        )?;

        ctx.accounts.state.round = ctx.accounts.state.round.wrapping_add(1);

        // TODO: Subtract bet_amount from user wallet

        Ok(())
    }

    pub fn on_coin_flipped(
        ctx: Context<CoinFlipResult>,
        vrf_round: u64,
        bet_amount: u64,
    ) -> anchor_lang::Result<()> {
        todo!()
    }
}

#[derive(Accounts)]
pub struct InitProgram<'info> {
    #[account(mut)]
    owner: Signer<'info>,

    #[account(
		init,
		payer = owner,
		space = 128,
		seeds = [ b"program_state" ],
		bump
	)]
    state: Account<'info, ProgramState>,

    system_program: Program<'info, System>,
}

#[derive(Accounts)]
pub struct CoinFlipRequest<'info> {
    #[account(mut)]
    user: Signer<'info>,

    #[account(mut, seeds = [ b"program_state" ], bump)]
    state: Account<'info, ProgramState>,

    #[account(
		init,
		payer = user,
		space = vrf_sdk::ACCOUNT_SIZE,
		seeds = [
			b"vrf",
			user.key().as_ref(),
			&state.round.to_be_bytes(),
		],
		bump,
	)]
    vrf: AccountLoader<'info, VrfState>,

    system_program: Program<'info, System>,
}

#[derive(Accounts)]
#[instruction(vrf_round: u64)]
pub struct CoinFlipResult<'info> {
    owner: Signer<'info>,

    /// CHECK: We checked that vrf PDA seeds contains user pubkey
    user: AccountInfo<'info>,

    #[account(mut, has_one = owner, seeds = [ b"program_state" ], bump)]
    state: Account<'info, ProgramState>,

    #[account(
		mut,
		close = user,
		seeds = [
			b"vrf",
			user.key().as_ref(),
			&vrf_round.to_be_bytes(),
		],
		bump
	)]
    vrf: AccountLoader<'info, VrfState>,
}

#[account]
pub struct ProgramState {
    owner: Pubkey,
    round: u64,
}
