[workspace]
members = [
    "."
]

[provider]
cluster = "devnet"
wallet = "~/.config/solana/id.json"

[programs.devnet]
anchor_using_vrf = "3gfec8ANuaWzkNhAR5QRjUvGqUjMYLJ3YnSVhgMkugqv"

[registry]
url = "https://anchor.projectserum.com"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 60000 ./tests/*.test.ts"

[test.validator]
url = "https://api.devnet.solana.com"

[test]
startup_wait = 15000
